[package]

name = "leveldb"
version = "0.3.8"
authors = [ "Florian Gilcher <florian.gilcher@asquera.de>" ]

description = "An interface for leveldb"

license = "MIT"
readme = "README.md"

[lib]

name = "leveldb"

[dependencies]

db_key = "0.0.4"

[[test]]
name = "tests"
