[package]

name = "leveldb"
version = "0.1.0"
authors = [ "florian.gilcher@asquera.de" ]

description = "An interface for leveldb"

license = "MIT"

[lib]

name = "leveldb"

[dependencies]

db_key = "0.0.1"
